services:
  - type: web
    name: n8n-with-supabase
    plan: free
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_ENCRYPTION_KEY
        value: ""  # Wypełnij w panelu Render
      - key: GENERIC_TIMEZONE
        value: "Europe/Warsaw"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: ""  # Wypełnij w panelu Render
      - key: WEBHOOK_URL
        value: "https://n8n-with-supabase.onrender.com"
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        value: "db.lvavxjzvezxzdeykxmto.supabase.co"
      - key: DB_POSTGRESDB_DATABASE
        value: "postgres"
      - key: DB_POSTGRESDB_USER
        value: "wshoq"
      - key: DB_POSTGRESDB_PASSWORD
        value: ""  # Wypełnij w panelu Render
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: SUPABASE_API_KEY
        value: ""  # Wypełnij w panelu Render
