services:
  - type: web
    name: n8n-with-supabase
    plan: free
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      # Główne zmienne n8n
      - key: N8N_ENCRYPTION_KEY
        value: ${N8N_ENCRYPTION_KEY}

      - key: GENERIC_TIMEZONE
        value: ${GENERIC_TIMEZONE}

      - key: N8N_BASIC_AUTH_ACTIVE
        value: ${N8N_BASIC_AUTH_ACTIVE}
      - key: N8N_BASIC_AUTH_USER
        value: ${N8N_BASIC_AUTH_USER}
      - key: N8N_BASIC_AUTH_PASSWORD
        value: ${N8N_BASIC_AUTH_PASSWORD}

      - key: WEBHOOK_URL
        value: ${WEBHOOK_URL}

      # Konfiguracja bazy danych Supabase
      - key: DB_TYPE
        value: ${DB_TYPE}
      - key: DB_POSTGRESDB_HOST
        value: ${DB_HOST}
      - key: DB_POSTGRESDB_DATABASE
        value: ${DB_NAME}
      - key: DB_POSTGRESDB_USER
        value: ${DB_USER}
      - key: DB_POSTGRESDB_PASSWORD
        value: ${DB_PASSWORD}
      - key: DB_POSTGRESDB_PORT
        value: "${DB_PORT}"

      # Wymuszamy poprawne prawa dostępu do pliku config
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"

      # (Opcjonalnie) dostęp do Supabase przez API, np. w HTTP request node
      - key: SUPABASE_API_KEY
        value: ${SUPABASE_API_KEY}
